name: Deploy docker image

on:
  push:
    branches:
      - 'main'

jobs:
    build_docker_image:
      runs-on: ubuntu-18.04
      defaults:
        run:
          working-directory: ./backend
      steps:

  #     Build JAR:
        - uses: actions/checkout@v1
        - name: set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
        - name: Maven Package
          run: mvn -B clean compile package -DskipTests

  #     Set global environment variables:
        - name: set global env
          id: global_env
          run: |
            echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}" | tr [:upper:] [:lower:]
            echo "::set-output name=GITHUB_REPO::${GITHUB_REPOSITORY}" | tr [:upper:] [:lower:]
            echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}" | tr [:upper:] [:lower:]
  #     Build Docker image:
        - name: Build and tag image
          run: |
            docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
        - name: Docker login
          run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

  #     Publish image to github package repository:
        - name: Publish image
          env:
            IMAGE_NAME: ${{ steps.global_env.outputs.GITHUB_REPO }}
          run: docker push "docker.pkg.github.com/${{ steps.global_env.outputs.GITHUB_REPO }}/${{ steps.global_env.outputs.IMAGE_NAME }}" 