name: CI to Docker Hub
on:
  push:
    branches: [ master ]
jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./backend
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     Build JAR:
        - uses: actions/checkout@v1
        - name: set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
        - name: Maven Package
          run: mvn -B clean compile package -DskipTests

  #     Set global environment variables:
        - name: set global env
          id: global_env
          run: |
            echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}" | tr [:upper:] [:lower:]
            echo "::set-output name=GITHUB_REPO::${GITHUB_REPOSITORY}" | tr [:upper:] [:lower:]
            echo "::set-output name=DOCKERHUB_IMAGE_NAME::${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}" | tr [:upper:] [:lower:]
  #     Build Docker image:
        - name: Build and tag image
          run: |
            docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
  #     Publish image to github package repository:
        - name: Publish image
          env:
            IMAGE_NAME: ${{ steps.global_env.outputs.GITHUB_REPO }}
  #       run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.global_env.outputs.IMAGE_NAME }}:${GITHUB_SHA::8}" 
          run: docker push "lordnani/${{ steps.global_env.outputs.GITHUB_REPO }}/${{ steps.global_env.outputs.IMAGE_NAME }}" 
